language: java

jdk: oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install: /bin/true

script:
  - echo "Start"
  - gradle clean build
  - echo "Done"

notifications:
  email: false